### ISSUE TITLE
页眉是undefined

### ISSUE THREAD

**Issue by Huo-zai-feng-lang-li** [Alessandro-Pang/vue-print-next#1]
勾选了打印页眉和页脚，显示undefined
![Clip_2024-07-15_17-10-20](https://github.com/user-attachments/assets/51e9129b-510c-43cd-a4f3-014908cf07d8)

**Comment by Alessandro-Pang** [comment]
感谢提醒，以修复默认 undefined 的问题，如果需要自定义，设置 popTitle: '自定义页眉即可'
