### ISSUE TITLE
有自动分页的选项吗？没有的话，如何手动分页？

### ISSUE THREAD

**Issue by qq2982476894** [Alessandro-Pang/vue-print-next#5]
![image](https://github.com/user-attachments/assets/fbf271c4-7e45-401b-95ef-d52e576926d4)
这是局部打印出来的效果，有滚动条。
![image](https://github.com/user-attachments/assets/8cd1cc5a-61aa-4547-bac8-5fd397356113)

打印样式用了page-break-after也是没有正确分页的。
@media print {
    #printMe {
      box-shadow: none;
      width: auto;
      height: auto !important;
      padding: 0;
      margin-bottom: 0;
      zoom: 0.8;
      background-color: transparent;
    }
    .pagebreak {
      page-break-after: always !important;
    }
  }

**Comment by Alessandro-Pang** [comment]
我推测你绑定 `id` 为 `printMe` 的元素不是最小容器

意思是，你需要将有滚动条的那个元素， `id` 设置为 `printMe`

**Comment by qq2982476894** [comment]
> 我推测你绑定 `id` 为 `printMe` 的元素不是最小容器
> 
> 意思是，你需要将有滚动条的那个元素， `id` 设置为 `printMe`
是的，我已经把id绑定到有滚动条的元素上了，高度是3021px，还是没有分页打印成功。
![image](https://github.com/user-attachments/assets/f8d78f60-3d34-4a95-b1b9-8543ff42e78b)

**Comment by Alessandro-Pang** [comment]
可以提供一下这个页面代码示例么

**Comment by Alessandro-Pang** [comment]
好的

**Comment by qq2982476894** [comment]
> ![image](https://private-user-images.githubusercontent.com/53659740/352980786-fbf271c4-7e45-401b-95ef-d52e576926d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxODkyMjUsIm5iZiI6MTcyMzE4ODkyNSwicGF0aCI6Ii81MzY1OTc0MC8zNTI5ODA3ODYtZmJmMjcxYzQtN2U0NS00MDFiLTk1ZWYtZDUyZTU3NjkyNmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA3MzUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NDA2MmVmYTFhODkxOTE0OTcwMDJkYmFjZmE0NTFlZGJkYjg2YWQwOTY4ZTY5MzUyOWU3MDM2MzlmMWU0YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ey_kDJ-E4Zs6UV39DAA_ccoQfC6CktBfeM8xkS9uMyA) 这是局部打印出来的效果，有滚动条。 ![image](https://private-user-images.githubusercontent.com/53659740/352981116-8cd1cc5a-61aa-4547-bac8-5fd397356113.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxODkyMjUsIm5iZiI6MTcyMzE4ODkyNSwicGF0aCI6Ii81MzY1OTc0MC8zNTI5ODExMTYtOGNkMWNjNWEtNjFhYS00NTQ3LWJhYzgtNWZkMzk3MzU2MTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA3MzUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4YWY1MzFkOGUxNmQyMjM3YjlmNTNiNTkwMjRlYjUwYjhkZmRlN2ZlMDIyMzVmY2ZkMzQwMDI2NzljOGJlZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6joTL7O2S671QXz_ed51b52dQcpJngd8dXEIihJWXEA)
> 
> 打印样式用了page-break-after也是没有正确分页的。 @media print { #printMe { box-shadow: none; width: auto; height: auto !important; padding: 0; margin-bottom: 0; zoom: 0.8; background-color: transparent; } .pagebreak { page-break-after: always !important; } }

j

> 好的

解决了 原项目样式里html设置了一个overflow:hidden。找半天才找到。服了

**Comment by Alessandro-Pang** [comment]
> 解决了 原项目样式里html设置了一个overflow:hidden。找半天才找到。服了

哈哈哈哈 🤣，解决了就好
