### ISSUE TITLE
我打印canvas地图一直是空白，大佬可以帮忙看看吗

### ISSUE THREAD

**Issue by NinjaJin** [Alessandro-Pang/vue-print-next#7]
![1730961749906](https://github.com/user-attachments/assets/ec7ec16a-f415-4203-b51b-836242a126bd)
![1730961794251](https://github.com/user-attachments/assets/39a015a4-d905-48c4-8b69-9ec086e93bd0)

**Comment by NinjaJin** [comment]
用.mapboxgl-container，#map，.mapboxgl-canvas都是空白TAT

**Comment by NinjaJin** [comment]
预览也是不显示地图，地图确实是异步渲染的，有办法解决吗

**Comment by NinjaJin** [comment]
![1730970419555](https://github.com/user-attachments/assets/58126c9e-bb09-42a3-bf84-d359ad40d271)

**Comment by Alessandro-Pang** [comment]
排查了一下问题，发现可能是因为地图是 `webgl` 导致 `canvas.toDataURL` 转换为空白了。

需要你在 **初始化地图资源** 之前，执行一下下面的代码：

```js
HTMLCanvasElement.prototype.getContext = (function (origFn) {
                return function (type, attributes) {
                    console.log(type)
                    if (type === "webgl") {
                        attributes = Object.assign({}, attributes, {
                            preserveDrawingBuffer: true,
                        });
                    }
                    return origFn.call(this, type, attributes);
                };
})(HTMLCanvasElement.prototype.getContext);
```

> 注意： 一定要在初始化资源之前，如果地图已经执行 `getContext` 在执行这段代码是不生效的

**Comment by Alessandro-Pang** [comment]
这是我用 百度地图 写的一个示例:

<img width="626" alt="image" src="https://github.com/user-attachments/assets/a1e73235-6aaf-4310-8cfa-41268b45f79b">
